[package]
name = "myrias"
version = "0.1.0"
authors = ["iCrawl <icrawltogo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.5"
serde = "1.0.98"
log = "0.4.8"
env_logger = "0.6.2"
rustflake = "0.1.1"

[profile.release]
lto = true
codegen-units = 1
