[package]
name = "myrias"
version = "0.1.0"
authors = ["iCrawl <icrawltogo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
serde = "1.0"
log = "0.4"
env_logger = "0.6"

[profile.release]
lto = true
codegen-units = 1
